base_dir: "{{playbook_dir | dirname }}"
dest_dir: "/home/ubuntu"
home_dir: "{{dest_dir}}/Prometheus"
compose_file: "{{home_dir}}/docker/prometheus.yml"
container_name: prometheus
restart_policy: '{{ lookup("env", "RESTART") }}'
