- name: intro to file module
  hosts: large
  vars:
    base_dir: /home/ubuntu
  tasks:
    - name: change ubuntu ownership to root
      become: true
      file:
        path: "{{base_dir}}"
        owner: root
        group: root
        state: directory
      register: output
    
    - name: create a file
      become: true
      file:
        path: "{{base_dir}}/test-file.txt"
        mode: '0655'
        state: absent
    
    - name: create a directory
      file:
        path: "{{base_dir}}/test_dir"
        mode: '0755'
        owner: ubuntu
        group: ubuntu
        state: directory