- name: Ansible facts and registering vars
  hosts: localhost
  vars:
    dict01:
      name: "shayan"
      age : 10
    
    dict02:
      name: "Ahmad"
  tasks:
    - name: show facts
      debug:
        var: ansible_facts
    

    - name: create a new dict combination
      set_fact:
        new_dict: "{{ dict01 | combine(dict02) }}"

    - name: double the age
      set_fact:
        doubled_age: "{{ new_dict.age * 2 }}"


    - name: show the new dict
      debug:
        msg : "{{new_dict}} is my new dict and this is doubled age : {doubled_age}} "

    - name:
      shell:
        cmd: ls /home/ubuntu
      register: result

    - name: show output
      debug:
       var: result.stdout_lines
