- name: Install Docker (Debian/Ubuntu)
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start and enable Docker service
  changed_when: yes
  when: ansible_os_family == "Debian"

- name: Add Docker repository (RedHat/CentOS)
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present
  
  when: ansible_os_family == "RedHat"
  

- name: Install Docker (RedHat/CentOS)
  yum:
    name: docker-ce
    state: present
  notify: Start and enable Docker service
  when: ansible_os_family == "RedHat"


- name: Add user to Docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
  when: user_name != ''

