- name: Intro to looping with dicts and hashes.
  hosts: webservers
  become: true
  vars_files:
    - "vars.yml"
  tasks:
  
    - name: create groups
      group:
        name: "{{item}}"
        state: present
      loop: "{{ group_list }}"
    
    - name: show users_dict
      debug:
        msg: "{{users_dict | dict2items }}"

    - name: create a list of users with the right group
      user:
        name: "{{item.value.name}}"
        state: present
        shell: /bin/bash
        group: "{{item.value.group}}"
      loop: "{{users_dict | dict2items}}"

    - name: create a list of users with the right group with literal values
      user:
        name: "{{item.name}}"
        state: present
        shell: /bin/bash
        group: "{{item.group}}"
      loop:
        - {'name': 'asqar', 'group': 'dev'}
        - {'name': 'faezeh', 'group': 'prod'}
    
    - name: create a list of users with the right group with lookup
      user:
        name: "{{item.value.name}}"
        state: present
        shell: /bin/bash
        group: "{{item.value.group}}"
      loop: "{{lookup('dict', users_dict)}}"
