- name: Intro to looping with dicts and hashes.
  hosts: webservers
  become: true
  vars_files:
    - "vars.yml"
  tasks:

    - name: debug nested list
      debug: 
        msg: "{{item}}"
      loop: '{{ ["test", ["two", "tests"] | flatten(1)}}'

    - name: debug nested list
      debug: 
        msg: "{{item}}"
      with_items: ["test", ["two", "tests"]]