---

- name: FIRST EVER PLAYBOOK
  hosts: large
  tasks:
    # - name: print hello ansible
    #   MODULE_NAME:
    #     MODULE_PROPERTIES:

    - name: Print hello ansible
      debug:
        msg: "Hello Ansibler"
    
    #  legacy way of running shell commands (for specific use-cases e.g (piping , etc))
    - name: Get hostnames
      shell: hostname
      register: ls #capture task output

    # the better module to execute shell commands or scripts.
    - name: Get hostnames
      command: hostname
      register: hostname

    - name: Print hello ansible
      debug:
        var: ls.stdout

    - name: exit ansible with a message
      fail:
        msg: "EXITED :)"

    ## tasks after fail won't get executed